name: Publish on releases

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15

      - name: Gradle build cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-build-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-build-

      - name: Gradle wrapper cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}

      - name: Build and publish to Bintray and Maven Central
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          OSSRH_USER_TOKEN: ${{ secrets.OSSRH_USER_TOKEN }}
          OSSRH_KEY: ${{ secrets.OSSRH_KEY }}
        run: ./gradlew -Pversion=${{ github.event.release.tag_name }} bintrayUpload
